# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

a_rebours_1 <- function(n) {
    invisible(.Call(`_introRcppBases_a_rebours_1`, n))
}

a_rebours_2 <- function(n) {
    invisible(.Call(`_introRcppBases_a_rebours_2`, n))
}

arithmetic_overflow <- function() {
    invisible(.Call(`_introRcppBases_arithmetic_overflow`))
}

bouclette <- function(n) {
    invisible(.Call(`_introRcppBases_bouclette`, n))
}

cast <- function(x, y) {
    invisible(.Call(`_introRcppBases_cast`, x, y))
}

cast_to_int <- function(x) {
    .Call(`_introRcppBases_cast_to_int`, x)
}

combien <- function(n) {
    invisible(.Call(`_introRcppBases_combien`, n))
}

divise <- function(a, b) {
    .Call(`_introRcppBases_divise`, a, b)
}

division_entiere <- function(a, b) {
    invisible(.Call(`_introRcppBases_division_entiere`, a, b))
}

float_types <- function() {
    invisible(.Call(`_introRcppBases_float_types`))
}

hello <- function() {
    invisible(.Call(`_introRcppBases_hello`))
}

int_types <- function() {
    invisible(.Call(`_introRcppBases_int_types`))
}

mini <- function(x, y) {
    .Call(`_introRcppBases_mini`, x, y)
}

non_signes <- function() {
    invisible(.Call(`_introRcppBases_non_signes`))
}

numeric_limits <- function() {
    invisible(.Call(`_introRcppBases_numeric_limits`))
}

operateurs_exotiques <- function(a) {
    invisible(.Call(`_introRcppBases_operateurs_exotiques`, a))
}

overflow <- function() {
    invisible(.Call(`_introRcppBases_overflow`))
}

petit_tableau <- function() {
    invisible(.Call(`_introRcppBases_petit_tableau`))
}

racine_carree <- function(x, eps = 1e-5) {
    .Call(`_introRcppBases_racine_carree`, x, eps)
}

somme_entiers <- function(a, b) {
    .Call(`_introRcppBases_somme_entiers`, a, b)
}

test_interval <- function(x, min, max) {
    .Call(`_introRcppBases_test_interval`, x, min, max)
}

test_positif <- function(x) {
    .Call(`_introRcppBases_test_positif`, x)
}

trois <- function(n) {
    invisible(.Call(`_introRcppBases_trois`, n))
}

uninit <- function() {
    .Call(`_introRcppBases_uninit`)
}

ze_loop <- function(n) {
    invisible(.Call(`_introRcppBases_ze_loop`, n))
}

zz <- function(n, z) {
    invisible(.Call(`_introRcppBases_zz`, n, z))
}

